import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

const supabase = createClient(supabaseUrl, supabaseServiceKey)

// Category slug to UUID mapping (will be populated after fetching categories)
let categoryMap: Record<string, string> = {}

const projects = [
  // Branding Projects
  {
    slug: "masaha-360-brand-campaign",
    title: "Masaha 360 – Brand Campaign",
    category_slug: "branding",
    short_description: "Comprehensive brand campaign for Masaha 360 showcasing equipment rental services and brand positioning",
    client: "Masaha Global",
    year: "2024",
    services: ["Brand Campaign", "Visual Identity", "Marketing Collateral", "Digital Assets"],
    cover_image_url: "/masaha-360-campaign-thumbnail-2.jpg",
    images: [
      "/masaha-360-campaign-Artboard-10.jpg",
      "/masaha-360-campaign-Artboard-20.jpg",
      "/masaha-360-campaign-Artboard-30.jpg",
      "/masaha-360-campaign-Artboard-40.jpg",
      "/masaha-360-campaign-Artboard-50.jpg",
      "/masaha-360-campaign-Artboard-60.jpg",
      "/masaha-360-campaign-Artboard-70.jpg",
      "/masaha-360-campaign-Artboard-80.jpg",
      "/masaha-360-campaign-Artboard-90.jpg",
      "/masaha-360-campaign-Artboard-100.jpg",
    ],
    challenge: "Create a compelling brand campaign for Masaha 360 that effectively communicates their equipment rental services while establishing a strong market presence in the industrial sector.",
    solution: "Developed a comprehensive brand campaign with cohesive visual identity, marketing collateral, and digital assets that position Masaha 360 as a trusted leader in equipment rental services.",
    process: [
      "Brand Strategy - Defined campaign messaging and positioning",
      "Visual Development - Created campaign visual language and assets",
      "Collateral Design - Designed marketing materials and touchpoints",
      "Digital Assets - Developed social media and web graphics",
      "Campaign Launch - Coordinated rollout across all channels",
    ],
    results: "The brand campaign successfully elevated Masaha 360's market presence, resulting in increased brand recognition and customer inquiries across the industrial equipment sector.",
    technologies: ["Adobe Illustrator", "Adobe Photoshop", "Adobe InDesign", "Figma"],
    testimonial_quote: "The brand campaign transformed how we present ourselves in the market. The visual identity is strong and memorable.",
    testimonial_author: "Masaha Global Team",
    testimonial_role: "Client",
    featured: true,
    published: true,
  },
  {
    slug: "perpetual-blessings-branding",
    title: "Branding: Perpetual Blessings",
    category_slug: "branding",
    short_description: "Complete brand identity design for Perpetual Blessings including logo, color palette, and brand guidelines",
    client: "Perpetual Blessings",
    year: "2024",
    services: ["Logo Design", "Brand Identity", "Brand Guidelines", "Visual System"],
    cover_image_url: "/images/Perpetual-Blessing-Thumbnail.jpg",
    images: [
      "/perpetual-blessings-1.jpg",
      "/perpetual-blessings-2.jpg",
      "/perpetual-blessings-3.jpg",
      "/perpetual-blessings-4.jpg",
      "/perpetual-blessings-5.jpg",
      "/perpetual-blessings-6.jpg",
      "/perpetual-blessings-7.jpg",
      "/perpetual-blessings-8.jpg",
      "/perpetual-blessings-9.jpg",
      "/perpetual-blessings-10.jpg",
      "/images/perpetual-blessings-11.jpg",
      "/images/perpetual-blessings-12.jpg",
    ],
    challenge: "Design a meaningful brand identity for Perpetual Blessings that reflects their mission and values while creating a memorable and versatile visual system.",
    solution: "Created a thoughtful brand identity with a distinctive logo, harmonious color palette, and comprehensive brand guidelines that ensure consistency across all applications.",
    process: [
      "Discovery - Explored brand values and target audience",
      "Concept Development - Created multiple logo concepts",
      "Refinement - Iterated based on feedback and testing",
      "Brand System - Developed complete visual identity system",
      "Guidelines - Documented brand standards and usage rules",
    ],
    results: "Delivered a complete brand identity that effectively communicates Perpetual Blessings' mission and provides a strong foundation for all brand communications.",
    technologies: ["Adobe Illustrator", "Figma", "Adobe InDesign", "Adobe Photoshop"],
    testimonial_quote: "The brand identity beautifully captures our essence. It's professional, meaningful, and works perfectly across all our materials.",
    testimonial_author: "Perpetual Blessings Team",
    testimonial_role: "Client",
    featured: false,
    published: true,
  },
  {
    slug: "Al-Musaha-AlMushtaraka-Co",
    title: "Al-Masaha AlMushtaraka-Branding",
    category_slug: "branding",
    short_description: "Annual report branding and design for Kuwait Bureau of Financial Controller with comprehensive financial oversight presentation",
    client: "Kuwait Bureau of Financial Controller",
    year: "2024",
    services: ["Branding", "Construction Branding"],
    cover_image_url: "/mmc-branding-1.jpg",
    images: [
      "/mmc-branding-1.jpg", "/mmc-branding-2.jpg", "/mmc-branding-3.jpg", "/mmc-branding-4.jpg",
      "/mmc-branding-5.jpg", "/mmc-branding-6.jpg", "/mmc-branding-7.jpg", "/mmc-branding-8.jpg",
      "/mmc-branding-9.jpg", "/mmc-branding-10.jpg", "/mmc-branding-11.jpg", "/mmc-branding-12.jpg",
      "/mmc-branding-13.jpg", "/mmc-branding-14.jpg", "/mmc-branding-15.jpg", "/mmc-branding-16.jpg",
    ],
    challenge: "Create a comprehensive annual report brand identity for the Kuwait Bureau of Financial Controller that clearly presents financial oversight, compliance, and performance data in an authoritative format.",
    solution: "Designed a professional government report with cohesive branding, detailed financial data presentation, compliance metrics, and performance indicators in an accessible, authoritative format.",
    process: [
      "Brand Development - Created report visual identity and guidelines",
      "Data Organization - Structured financial information logically",
      "Design System - Developed government-appropriate visual design",
      "Compliance Review - Ensured adherence to reporting standards",
      "Final Production - Prepared report for official distribution",
    ],
    results: "The annual report successfully communicated the Bureau's financial oversight activities and met all government reporting requirements with clarity and professionalism.",
    technologies: ["Adobe InDesign", "Adobe Illustrator", "Adobe Photoshop"],
    featured: false,
    published: true,
  },
  {
    slug: "action-pro-film-directory",
    title: "Action Pro – Film Directory Company",
    category_slug: "branding",
    short_description: "Professional brand identity for Action Pro, a film directory company connecting film industry professionals",
    client: "Action Pro",
    year: "2024",
    services: ["Brand Identity", "Logo Design", "Entertainment Branding", "Visual System"],
    cover_image_url: "/action-thumbnail.png",
    images: [
      "/action-branding-1.jpg", "/action-branding-2.jpg", "/action-branding-3.jpg", "/action-branding-4.jpg",
      "/action-branding-5.jpg", "/action-branding-6.jpg", "/action-branding-7.jpg", "/action-branding-8.jpg",
      "/action-branding-9.jpg", "/action-branding-10.jpg", "/action-branding-11.jpg", "/action-branding-12.jpg",
    ],
    challenge: "Design a professional brand identity for a film directory company that conveys industry expertise, credibility, and connects with film professionals.",
    solution: "Created a bold, cinematic brand identity with a distinctive logo, professional color scheme, and visual system that reflects the dynamic nature of the film industry.",
    process: [
      "Industry Research - Analyzed film industry branding trends",
      "Logo Design - Developed cinematic, professional logo",
      "Visual Identity - Created comprehensive brand system",
      "Applications - Designed business materials and digital assets",
      "Guidelines - Documented brand standards for consistency",
    ],
    results: "The brand identity established Action Pro as a credible film industry resource, facilitating connections between professionals and building industry recognition.",
    technologies: ["Adobe Illustrator", "Figma", "Adobe Photoshop"],
    testimonial_quote: "The branding gives us instant credibility in the film industry. It's professional, memorable, and perfectly represents what we do.",
    testimonial_author: "Action Pro Team",
    testimonial_role: "Client",
    featured: false,
    published: true,
  },
  {
    slug: "66-battalion-commandos",
    title: "66 Battalion – Commandos 25",
    category_slug: "branding",
    short_description: "Military unit branding for 66 Battalion Commandos 25 with strong, authoritative visual identity",
    client: "66 Battalion",
    year: "2024",
    services: ["Military Branding", "Emblem Design", "Unit Identity", "Tactical Design"],
    cover_image_url: "/images/battalion/background.jpg",
    images: [
      "/images/battalion/background.jpg", "/images/battalion/illustrations.jpg", "/images/battalion/shield-sketch.jpg",
      "/images/battalion/logo-grayscale.jpg", "/images/battalion/logo-full-color.jpg", "/images/battalion/color-codes.jpg",
      "/images/battalion/typography.jpg", "/images/battalion/flag.jpg", "/images/battalion/banner.jpg", "/images/battalion/pattern.jpg",
    ],
    challenge: "Design a powerful military unit brand identity that conveys strength, unity, and professionalism while honoring military traditions.",
    solution: "Created a strong, authoritative brand identity with a distinctive battalion emblem, tactical color scheme, and applications that instill pride and unit cohesion.",
    process: [
      "Military Research - Studied military branding traditions",
      "Emblem Design - Developed powerful battalion emblem",
      "Visual System - Created tactical, professional design system",
      "Applications - Designed unit materials and insignia",
      "Standards - Documented military branding guidelines",
    ],
    results: "The brand identity successfully strengthened unit cohesion and pride, creating a distinctive visual identity that honors military traditions.",
    technologies: ["Adobe Illustrator", "Adobe Photoshop"],
    testimonial_quote: "The emblem and branding perfectly represent our battalion's strength and unity. It's become a source of pride for all our members.",
    testimonial_author: "66 Battalion Leadership",
    testimonial_role: "Client",
    featured: false,
    published: true,
  },
  {
    slug: "the-best-juice",
    title: "The Best Juice | عصير ذا بست",
    category_slug: "branding",
    short_description: "Complete brand identity for The Best Juice, a fresh juice bar featuring Arabic and English branding",
    client: "The Best Juice",
    year: "2024",
    services: ["Brand Identity", "Logo Design", "Bilingual Design", "Food & Beverage Branding"],
    cover_image_url: "/juice-01.png",
    images: [
      "/juice-01.png", "/juice-02.png", "/juice-03.png", "/juice-04.png",
      "/juice-05.png", "/juice-06.png", "/juice-07.png", "/juice-08.png",
      "/juice-10.png", "/juice-11.png", "/juice-12.png", "/juice-13.png",
    ],
    challenge: "Create a vibrant, appealing brand identity for a juice bar that works seamlessly in both Arabic and English while conveying freshness, quality, and health.",
    solution: "Developed a fresh, colorful brand identity with bilingual logo design, vibrant color palette inspired by fresh fruits, and versatile applications across menus, packaging, and signage.",
    process: [
      "Brand Discovery - Explored juice bar market and target audience",
      "Concept Development - Created bilingual logo concepts",
      "Color System - Developed fresh, fruit-inspired color palette",
      "Applications - Designed menus, packaging, and store graphics",
      "Brand Guidelines - Documented bilingual usage standards",
    ],
    results: "The brand identity successfully positioned The Best Juice as a fresh, quality-focused juice bar, attracting health-conscious customers and creating strong brand recognition.",
    technologies: ["Adobe Illustrator", "Adobe Photoshop", "Adobe InDesign"],
    testimonial_quote: "The branding perfectly captures our fresh, healthy vibe. Customers love the design and it works beautifully in both languages.",
    testimonial_author: "The Best Juice Team",
    testimonial_role: "Client",
    featured: false,
    published: true,
  },
  {
    slug: "fateer-wa-teer-restaurant",
    title: "Fateer wa teer Restaurant - (الكويت) مطعم فطير وطير",
    category_slug: "branding",
    short_description: "Traditional Arabic restaurant branding for Fateer wa teer in Kuwait, featuring cultural design elements",
    client: "Fateer wa teer Restaurant",
    year: "2024",
    services: ["Restaurant Branding", "Arabic Design", "Menu Design", "Cultural Branding"],
    cover_image_url: "/fateer-wa-teer-thumbnail.png",
    images: ["/fateer-wa-teer-1.png", "/fateer-wa-teer-2.jpg", "/fateer-wa-teer-3.jpg", "/fateer-wa-teer-4.png"],
    challenge: "Create an authentic Arabic restaurant brand identity that honors traditional Kuwaiti culinary culture while appealing to modern diners.",
    solution: "Developed a culturally rich brand identity with Arabic calligraphy, traditional patterns, warm colors, and menu designs that celebrate Kuwaiti food heritage.",
    process: [
      "Cultural Research - Studied Kuwaiti culinary traditions",
      "Design Development - Created Arabic-focused visual identity",
      "Menu Design - Designed traditional yet modern menu layouts",
      "Interior Graphics - Developed restaurant signage and decor",
      "Brand Guidelines - Documented cultural design standards",
    ],
    results: "The brand identity successfully connects with local customers through authentic cultural representation while attracting new diners with its modern presentation.",
    technologies: ["Adobe Illustrator", "Adobe InDesign", "Adobe Photoshop"],
    testimonial_quote: "The branding beautifully represents our traditional food with a modern touch. Our customers feel the authentic Kuwaiti spirit.",
    testimonial_author: "Fateer wa teer Team",
    testimonial_role: "Client",
    featured: false,
    published: true,
  },
  // Print Design Projects
  {
    slug: "masaha-company-profile",
    title: "Company Profile – Masaha Global",
    category_slug: "print-design",
    short_description: "Professional company profile showcasing Masaha Global's services, capabilities, and market position",
    client: "Masaha Global",
    year: "2024",
    services: ["Company Profile Design", "Layout Design", "Print Production", "Content Organization"],
    cover_image_url: "/masaha-company-profile-thumbnail.png",
    images: ["/masaha-company-profile-full.jpg"],
    pdf_url: "/masaha-company-profile.pdf",
    challenge: "Design a comprehensive company profile that effectively presents Masaha Global's extensive services, capabilities, and market leadership in the equipment rental industry.",
    solution: "Created a professional, well-structured company profile with clear information hierarchy, engaging layouts, and high-quality imagery that showcases Masaha Global's expertise and market position.",
    process: [
      "Content Strategy - Organized company information and messaging",
      "Layout Design - Developed grid system and page templates",
      "Visual Design - Applied brand identity and professional aesthetics",
      "Print Preparation - Prepared high-resolution files for production",
      "Quality Control - Reviewed proofs and final production",
    ],
    results: "The company profile successfully communicates Masaha Global's value proposition and has become an essential tool for business development and client presentations.",
    technologies: ["Adobe InDesign", "Adobe Illustrator", "Adobe Photoshop"],
    testimonial_quote: "The company profile perfectly represents our brand and capabilities. It's been instrumental in winning new business.",
    testimonial_author: "Masaha Global Team",
    testimonial_role: "Client",
    featured: true,
    published: true,
  },
  {
    slug: "masaha-rental-equipment-brochure",
    title: "Rental Equipment Brochure (Masaha)",
    category_slug: "print-design",
    short_description: "Detailed equipment rental brochure showcasing Masaha's comprehensive inventory and services",
    client: "Masaha Global",
    year: "2024",
    services: ["Brochure Design", "Product Catalog", "Print Layout", "Technical Specifications"],
    cover_image_url: "/masaha-rental-brochure-thumbnail.png",
    images: ["/masaha-rental-brochure-full.jpg"],
    pdf_url: "/masaha-rental-equipment-brochure.pdf",
    challenge: "Design an informative rental equipment brochure that clearly presents Masaha's extensive inventory while maintaining visual appeal and easy navigation for potential clients.",
    solution: "Developed a well-organized brochure with clear equipment categories, detailed specifications, high-quality product images, and intuitive layout that helps clients quickly find the equipment they need.",
    process: [
      "Content Organization - Categorized equipment and specifications",
      "Layout Design - Created structured templates for equipment listings",
      "Photography Integration - Incorporated professional equipment photos",
      "Technical Details - Formatted specifications for clarity",
      "Print Production - Prepared files for professional printing",
    ],
    results: "The rental equipment brochure streamlined the client inquiry process and increased equipment rental bookings by providing clear, accessible information.",
    technologies: ["Adobe InDesign", "Adobe Photoshop", "Adobe Illustrator"],
    featured: false,
    published: true,
  },
  {
    slug: "2025-wall-calendar",
    title: "2025 Wall Calendar",
    category_slug: "print-design",
    short_description: "Custom designed 2025 wall calendar for Masaha Global with branded design, Kuwait holidays, and functional layout",
    client: "Masaha Global",
    year: "2024",
    services: ["Calendar Design", "Layout Design", "Print Production", "Brand Integration"],
    cover_image_url: "/2025-calendar-thumbnail-new.jpg",
    images: ["/2025-calendar-full.jpg"],
    pdf_url: "/2025-wall-calendar.pdf",
    challenge: "Design an attractive and functional 2025 wall calendar that serves as both a practical tool and a year-round brand reminder for Masaha Global's clients and partners in Kuwait.",
    solution: "Created a beautifully designed desk-style wall calendar featuring Masaha's red and white brand colors, monthly layouts with ample writing space, Kuwait public holidays clearly marked, and equipment imagery showcasing the company's rental services.",
    process: [
      "Concept Development - Defined calendar theme aligned with Masaha's construction equipment brand",
      "Holiday Research - Compiled all Kuwait public holidays for 2025 including Islamic observances",
      "Layout Design - Designed clean monthly grids with bilingual information",
      "Visual Design - Applied Masaha brand colors, logo, and equipment photography",
      "Production Preparation - Set up files for high-quality calendar printing",
    ],
    results: "The 2025 wall calendar was well-received by clients and partners, providing year-round brand visibility and serving as a practical, appreciated gift that keeps Masaha Global top-of-mind.",
    technologies: ["Adobe InDesign", "Adobe Illustrator", "Adobe Photoshop"],
    testimonial_quote: "The calendar design is beautiful and functional. Our clients love it and it keeps our brand visible all year long.",
    testimonial_author: "Masaha Global Team",
    testimonial_role: "Client",
    featured: false,
    published: true,
  },
  {
    slug: "al-waha-schools-magazine",
    title: "Al Waha Schools – Magazine",
    category_slug: "print-design",
    short_description: "Educational magazine design for Al Waha Schools featuring student work, school news, and educational content",
    client: "Al Waha Schools",
    year: "2024",
    services: ["Magazine Design", "Editorial Layout", "Educational Publishing", "Print Production"],
    cover_image_url: "/al-waha-magazine-thumbnail.jpg",
    images: ["/al-waha-magazine-cover.jpg", "/al-waha-magazine-spreads.jpg", "/al-waha-magazine-features.jpg"],
    challenge: "Design an engaging school magazine that showcases student achievements, school activities, and educational content while maintaining professional quality and visual appeal.",
    solution: "Created a vibrant, well-organized magazine with dynamic layouts, student-friendly design, clear content sections, and professional production quality that celebrates school community.",
    process: [
      "Content Planning - Organized magazine sections and features",
      "Layout Design - Developed flexible grid system for varied content",
      "Visual Design - Applied school branding with engaging aesthetics",
      "Editorial Design - Designed article layouts and photo spreads",
      "Print Production - Prepared files for professional printing",
    ],
    results: "The magazine successfully engaged the school community, showcasing student work and school activities in a professional, appealing format that became a valued keepsake.",
    technologies: ["Adobe InDesign", "Adobe Photoshop", "Adobe Illustrator"],
    testimonial_quote: "The magazine design beautifully showcases our students and school community. Parents and students love it!",
    testimonial_author: "Al Waha Schools Administration",
    testimonial_role: "Client",
    featured: false,
    published: true,
  },
  {
    slug: "almasaha-almushtarakah-profile",
    title: "Al-Masaha Al-Mushtarakah Company Profile",
    category_slug: "print-design",
    short_description: "Comprehensive company profile for Al-Masaha Al-Mushtarakah showcasing services and corporate capabilities",
    client: "Al-Masaha Al-Mushtarakah",
    year: "2024",
    services: ["Company Profile Design", "Corporate Design", "Layout Design", "Print Production"],
    cover_image_url: "/almasaha-mushtarakah-profile-thumbnail-new.png",
    images: [],
    pdf_url: "/al-masaha-mushtarakah-profile.pdf",
    challenge: "Design a professional company profile for Al-Masaha Al-Mushtarakah that effectively presents their services, capabilities, and market position to potential clients and partners.",
    solution: "Created a comprehensive, professionally designed company profile with clear information architecture, engaging layouts, and high-quality presentation that showcases corporate strengths.",
    process: [
      "Content Strategy - Organized company information and services",
      "Layout Design - Developed professional grid and page templates",
      "Visual Design - Applied corporate branding and aesthetics",
      "Print Preparation - Prepared high-resolution production files",
      "Quality Control - Reviewed proofs and final production",
    ],
    results: "The company profile successfully communicates Al-Masaha Al-Mushtarakah's value proposition and has become an essential business development tool for client presentations.",
    technologies: ["Adobe InDesign", "Adobe Illustrator", "Adobe Photoshop"],
    testimonial_quote: "The company profile perfectly represents our business. It's professional, comprehensive, and has helped us win new contracts.",
    testimonial_author: "Al-Masaha Al-Mushtarakah Team",
    testimonial_role: "Client",
    featured: false,
    published: true,
  },
  // Social Media Projects
  {
    slug: "instagram-campaign",
    title: "Instagram Marketing Campaign",
    category_slug: "social-media",
    short_description: "Social media graphics for Instagram marketing campaign",
    client: "Fashion Brand",
    year: "2024",
    services: ["Social Media Graphics", "Content Design", "Brand Consistency"],
    cover_image_url: "/instagram-posts.jpg",
    images: ["/instagram-feed-design.jpg", "/instagram-stories.jpg", "/instagram-carousel.jpg"],
    challenge: "Create a cohesive Instagram campaign that drives engagement and brand awareness while maintaining consistency across feed posts, stories, and carousel formats for a fashion brand's seasonal launch.",
    solution: "Developed a comprehensive visual system with consistent color palettes, typography, and design elements that work seamlessly across all Instagram formats. Created templates for easy content creation and brand consistency.",
    process: [
      "Brand Analysis - Studied brand guidelines and target audience",
      "Content Planning - Developed content calendar and themes",
      "Design System - Created templates for posts, stories, and carousels",
      "Asset Creation - Designed campaign graphics and animations",
      "Performance Tracking - Monitored engagement and optimized designs",
    ],
    results: "The campaign achieved 250% increase in engagement rate, 180% growth in followers, and generated over 1M impressions in the first month.",
    technologies: ["Figma", "Adobe Photoshop", "Canva", "Adobe After Effects"],
    testimonial_quote: "The Instagram campaign exceeded all our expectations. The designs are stunning and our engagement has never been higher.",
    testimonial_author: "Emma Rodriguez",
    testimonial_role: "Social Media Manager, Fashion Brand",
    featured: true,
    published: true,
  },
  // Presentations Projects
  {
    slug: "sany-partnership-milestones",
    title: "Partnership with SANY and Major Milestones",
    category_slug: "presentations",
    short_description: "Strategic presentation showcasing partnership achievements and major milestones with SANY",
    client: "SANY Partnership",
    year: "2024",
    services: ["Presentation Design", "Data Visualization", "Milestone Tracking", "Corporate Design"],
    cover_image_url: "/sany-partnership-thumbnail.png",
    images: ["/sany-partnership-cover.jpg", "/sany-partnership-milestones.jpg", "/sany-partnership-data.jpg"],
    pdf_url: "/sany-partnership-presentation.pdf",
    challenge: "MASAHA, part of the Fouad Al Ghanim & Sons group, needed to create a comprehensive presentation documenting their partnership journey with SANY since the agency contract was signed on May 15, 2017.",
    solution: "Developed a data-rich presentation showcasing the partnership's success: 999 units of SANY equipment purchased totaling $128,645,981 from 2017 to December 2023.",
    process: [
      "Timeline Development - Created chronological partnership journey from May 15, 2017 contract signing to present",
      "Data Analysis - Compiled and categorized 999 equipment purchases across 50+ equipment models and types",
      "Financial Visualization - Designed charts showing $128.6M total investment and year-by-year purchase trends",
      "Competitive Analysis - Mapped MASAHA's positioning against key competitors",
      "Product Portfolio Showcase - Organized comprehensive equipment catalog by category and capacity",
      "Brand Integration - Incorporated MASAHA and SANY corporate identities throughout",
    ],
    results: "The presentation successfully demonstrated MASAHA's transformation into Kuwait's leading SANY dealer with nearly 1,000 units deployed.",
    technologies: ["PowerPoint", "Figma", "Adobe Illustrator"],
    testimonial_quote: "The presentation beautifully showcased our partnership journey from 2017 to present.",
    testimonial_author: "Partnership Development Team",
    testimonial_role: "MASAHA Global",
    featured: true,
    published: true,
  },
  {
    slug: "dashboard-reporting-kpis",
    title: "Dashboard Reporting KPIs",
    category_slug: "presentations",
    short_description: "Comprehensive dashboard reporting system for tracking key performance indicators across 12 business departments",
    client: "Masaha Global",
    year: "2024",
    services: ["Dashboard Design", "KPI Visualization", "Data Analytics", "Performance Tracking", "Business Intelligence"],
    cover_image_url: "/dashboard-kpis-thumbnail.png",
    images: ["/dashboard-kpis-thumbnail.png"],
    pdf_url: "/dashboard-reporting-kpis.pdf",
    challenge: "Masaha Global needed a unified dashboard reporting system to track and monitor KPIs across 12 diverse departments.",
    solution: "Developed a comprehensive TV Dashboard system that enables faster, data-driven decisions at all levels - management, operational, and frontline.",
    process: [
      "Requirements Analysis - Identified critical KPIs for each of 12 departments",
      "Dashboard Architecture - Designed unified TV dashboard system for real-time monitoring",
      "KPI Definition - Defined department-specific metrics",
      "Data Visualization - Created intuitive visual representations for complex metrics",
      "Integration Planning - Established data connectivity for live monitoring",
      "Department Customization - Tailored each dashboard with relevant KPIs",
    ],
    results: "Successfully deployed a comprehensive dashboard system covering 12 departments that improved organizational performance through better cost control and target setting.",
    technologies: ["PowerPoint", "Data Analytics Tools", "Business Intelligence Software", "Dashboard Design Tools"],
    testimonial_quote: "The dashboard system has transformed how we monitor and manage our business operations.",
    testimonial_author: "Operations Director",
    testimonial_role: "Masaha Global",
    featured: false,
    published: true,
  },
  {
    slug: "new-kuwait-strategic-development",
    title: "New Kuwait – Strategic Development 2035",
    category_slug: "presentations",
    short_description: "Strategic development presentation for Kuwait's 2035 vision and major infrastructure projects",
    client: "Masaha Equipment Co.",
    year: "2024",
    services: ["Strategic Presentation", "Vision Communication", "Development Planning", "Government Design"],
    cover_image_url: "/new-kuwait-2035-thumbnail.png",
    images: ["/kuwait-2035-vision.jpg", "/kuwait-2035-initiatives.jpg", "/kuwait-2035-roadmap.jpg"],
    pdf_url: "/new-kuwait-2035.pdf",
    challenge: "Masaha Equipment Co. needed a comprehensive presentation to communicate Kuwait's Vision 2035 strategic development plan to government stakeholders.",
    solution: "Developed a strategic presentation showcasing Kuwait's transformation into a leading regional financial, commercial, and cultural hub by 2035.",
    process: [
      "Vision Overview - Introduced New Kuwait 2035 transformation goals",
      "Strategic Sectors - Identified six key development areas",
      "Project Portfolio - Detailed major initiatives with investment values",
      "Market Analysis - Forecasted 3,000 machine requirements over 5 years",
      "Partnership Requirements - Outlined 3-year payment facilities and flexible product selection needs",
    ],
    results: "Successfully presented Kuwait's ambitious $189+ billion development portfolio across strategic sectors.",
    technologies: ["PowerPoint", "Figma", "Adobe Illustrator"],
    testimonial_quote: "The presentation powerfully communicates Kuwait's vision for transformative development.",
    testimonial_author: "Masaha Equipment Co.",
    testimonial_role: "Client",
    featured: false,
    published: true,
  },
  {
    slug: "sany-business-plan-kuwait",
    title: "Business Plan – SANY Commercial Trucks Factory – Kuwait",
    category_slug: "presentations",
    short_description: "Comprehensive business plan presentation for SANY commercial trucks factory establishment in Kuwait",
    client: "SANY Kuwait",
    year: "2024",
    services: ["Business Plan Design", "Financial Presentation", "Market Analysis", "Strategic Planning"],
    cover_image_url: "/sany-business-plan-thumbnail.png",
    images: ["/sany-business-plan-overview.jpg", "/sany-business-plan-financials.jpg", "/sany-business-plan-market.jpg"],
    pdf_url: "/sany-business-plan.pdf",
    challenge: "Develop a comprehensive business plan presentation for establishing a SANY commercial trucks factory in Kuwait.",
    solution: "Created a comprehensive business plan presentation with thorough market analysis, detailed financial projections, operational roadmap, and risk assessment.",
    process: [
      "Research - Analyzed market opportunity and competition",
      "Financial Modeling - Developed projections and ROI analysis",
      "Strategy Development - Outlined operational and growth plans",
      "Presentation Design - Created professional, data-rich slides",
      "Executive Preparation - Refined for investor presentations",
    ],
    results: "The business plan presentation successfully secured stakeholder approval and investment for the SANY commercial trucks factory project in Kuwait.",
    technologies: ["PowerPoint", "Excel", "Figma", "Adobe Illustrator"],
    featured: false,
    published: true,
  },
  {
    slug: "almasaha-annual-budget",
    title: "Al-Masaha Annual Budget",
    category_slug: "presentations",
    short_description: "Annual budget presentation for Al-Masaha with financial planning and resource allocation",
    client: "Al-Masaha",
    year: "2024",
    services: ["Budget Presentation", "Financial Planning", "Resource Allocation", "Executive Reporting"],
    cover_image_url: "/almasaha-budget-thumbnail.jpg",
    images: ["/almasaha-budget-overview.jpg", "/almasaha-budget-allocation.jpg", "/almasaha-budget-projections.jpg"],
    challenge: "Design a clear annual budget presentation that effectively communicates financial planning, resource allocation, and budget justification to executives and stakeholders.",
    solution: "Created a well-structured budget presentation with clear financial breakdowns, allocation visualizations, and comparative analysis.",
    process: [
      "Data Collection - Gathered budget data and requirements",
      "Financial Analysis - Analyzed spending patterns and needs",
      "Visualization - Created clear charts and allocation graphics",
      "Narrative Development - Built compelling budget justification",
      "Review Process - Refined based on finance team feedback",
    ],
    results: "The budget presentation streamlined the approval process and provided clear financial guidance for Al-Masaha's annual planning and resource allocation.",
    technologies: ["PowerPoint", "Excel", "Figma"],
    testimonial_quote: "The budget presentation made our financial planning clear and accessible. It significantly improved our approval process.",
    testimonial_author: "Al-Masaha Finance Team",
    testimonial_role: "Client",
    featured: false,
    published: true,
  },
  {
    slug: "investor-pitch-deck",
    title: "Investor Pitch Deck",
    category_slug: "presentations",
    short_description: "Professional pitch deck for startup funding",
    client: "StartupCo",
    year: "2024",
    services: ["Presentation Design", "Data Visualization", "Storytelling"],
    cover_image_url: "/pitch-deck-presentation.png",
    images: ["/pitch-deck-cover.jpg", "/pitch-deck-slides.jpg", "/pitch-deck-charts.jpg"],
    challenge: "Design a compelling investor pitch deck that clearly communicates StartupCo's value proposition, market opportunity, and financial projections to secure Series A funding.",
    solution: "Created a visually striking presentation with clear narrative flow, professional data visualizations, and consistent branding.",
    process: [
      "Story Development - Crafted narrative arc and key messages",
      "Content Organization - Structured slides for maximum impact",
      "Visual Design - Designed slides with professional aesthetics",
      "Data Visualization - Created clear, impactful charts and graphs",
      "Refinement - Iterated based on practice presentations",
    ],
    results: "StartupCo successfully secured $5M in Series A funding. Investors praised the clarity and professionalism of the presentation.",
    technologies: ["Figma", "PowerPoint", "Keynote", "Adobe Illustrator"],
    testimonial_quote: "The pitch deck was instrumental in our fundraising success. It perfectly communicated our vision and the design made our data come alive.",
    testimonial_author: "David Park",
    testimonial_role: "CEO, StartupCo",
    featured: false,
    published: true,
  },
  // Videos & Motion Projects
  {
    slug: "brand-animation",
    title: "Brand Animation Video",
    category_slug: "videos-motion",
    short_description: "Animated brand video for social media",
    client: "Creative Agency",
    year: "2024",
    services: ["Motion Graphics", "Video Editing", "Animation"],
    cover_image_url: "/abstract-motion-graphics.png",
    images: ["/motion-graphics-storyboard.jpg"],
    challenge: "Create an engaging 60-second brand animation that captures the creative agency's innovative spirit and showcases their services in a memorable way for social media platforms.",
    solution: "Developed a dynamic motion graphics video with smooth transitions, vibrant colors, and kinetic typography.",
    process: [
      "Concept Development - Created storyboard and animation concepts",
      "Script Writing - Developed concise, impactful messaging",
      "Design Assets - Created graphic elements and style frames",
      "Animation - Brought designs to life with motion graphics",
      "Sound Design - Added music and sound effects for impact",
    ],
    results: "The brand animation video generated 500K+ views across social platforms, increased website traffic by 85%, and became the agency's most shared content piece.",
    technologies: ["After Effects", "Cinema 4D", "Premiere Pro", "Illustrator"],
    testimonial_quote: "The animation perfectly captures our brand energy. It's been our most effective marketing asset and clients love it.",
    testimonial_author: "Lisa Thompson",
    testimonial_role: "Creative Director, Creative Agency",
    featured: true,
    published: true,
  },
  // Photography Projects
  {
    slug: "product-photography",
    title: "Product Photography Session",
    category_slug: "photography",
    short_description: "Professional product photography for e-commerce",
    client: "E-commerce Store",
    year: "2024",
    services: ["Product Photography", "Photo Editing", "Retouching"],
    cover_image_url: "/placeholder.svg?height=400&width=600",
    images: [],
    challenge: "Create high-quality product photography that showcases e-commerce products in the best light, maintains consistency across the catalog, and drives conversions.",
    solution: "Executed a professional photography session with controlled lighting, multiple angles, and lifestyle shots.",
    process: [
      "Pre-Production - Planned shot list and lighting setups",
      "Photography Session - Captured products from multiple angles",
      "Selection - Curated best shots for each product",
      "Editing - Color correction and background removal",
      "Retouching - Final polish and consistency checks",
    ],
    results: "The professional product photography increased conversion rates by 45%, reduced return rates by 30%, and elevated the brand's premium positioning.",
    technologies: ["Canon EOS R5", "Profoto Lighting", "Adobe Lightroom", "Adobe Photoshop"],
    testimonial_quote: "The product photos transformed our online store. Sales increased immediately and customers comment on how professional everything looks.",
    testimonial_author: "Jennifer Martinez",
    testimonial_role: "Owner, E-commerce Store",
    featured: false,
    published: true,
  },
  {
    slug: "alia-landscape-company",
    title: "Alia Landscape Company",
    category_slug: "photography",
    short_description: "On-site photography documenting Alia Botanicals landscape maintenance operations, capturing the team at work across residential properties in Kuwait.",
    client: "Alia Botanicals",
    year: "2024",
    services: ["On-Site Photography", "Corporate Documentation", "Brand Photography", "Outdoor Shooting"],
    cover_image_url: "/alia-landscape-01.jpg",
    images: [
      "/alia-landscape-01.jpg", "/alia-landscape-10.jpg", "/alia-landscape-08.jpg", "/alia-landscape-15.jpg",
      "/alia-landscape-04.jpg", "/alia-landscape-05.jpg", "/alia-landscape-02.jpg", "/alia-landscape-03.jpg",
      "/alia-landscape-12.jpg", "/alia-landscape-06.jpg", "/alia-landscape-09.jpg", "/alia-landscape-07.jpg",
      "/alia-landscape-16.jpg", "/alia-landscape-11.jpg", "/alia-landscape-13.jpg", "/alia-landscape-14.jpg",
      "/alia-landscape-17.jpg",
    ],
    challenge: "Capture the day-to-day operations of Alia Botanicals' landscape maintenance team across a large residential property in Kuwait.",
    solution: "Conducted a full-day on-site photography shoot using elevated angles and close-up perspectives to document hedge trimming, lawn care, and team coordination.",
    process: [
      "Location Scouting - Identified key vantage points across the property",
      "Shoot Planning - Coordinated with the team to capture natural workflow",
      "Photography - Shot aerial, mid-range, and close-up perspectives",
      "Brand Focus - Emphasized branded uniforms, signage, and vehicle wrap",
      "Post-Production - Colour-corrected and edited for consistent, vibrant output",
    ],
    results: "Delivered a comprehensive library of professional photographs used for social media, the company website, and marketing materials.",
    technologies: ["Canon EOS R5", "Adobe Lightroom", "Adobe Photoshop"],
    testimonial_quote: "The photos perfectly capture the quality of our work and the professionalism of our team. We use them across all our marketing channels.",
    testimonial_author: "Alia Botanicals Team",
    testimonial_role: "Client",
    featured: true,
    published: true,
  },
  // Web Design Projects
  {
    slug: "razan-fashion",
    title: "Razan Fashion",
    category_slug: "web-design",
    short_description: "Modern modest fashion e-commerce platform specializing in hijabs and Islamic clothing with seamless shopping experience and payment integration.",
    client: "Razan Fashion",
    year: "2024",
    services: ["E-commerce Development", "React Development", "Payment Integration", "UI/UX Design"],
    cover_image_url: "/razan-fashion-home.jpg",
    images: ["/razan-fashion-home.jpg", "/razan-fashion-products.jpg", "/razan-fashion-checkout.jpg"],
    external_link: "https://razan-fashion.vercel.app",
    challenge: "Create a modern e-commerce platform that caters to the modest fashion market while providing a seamless shopping experience with secure payment integration.",
    solution: "Built a responsive React-based e-commerce platform with integrated payment processing, product filtering, and a clean, elegant design.",
    process: [
      "Discovery - Researched modest fashion market and user preferences",
      "Design - Created wireframes and high-fidelity mockups",
      "Development - Built React frontend with payment integration",
      "Testing - Conducted user testing and performance optimization",
      "Launch - Deployed and monitored initial user feedback",
    ],
    results: "Successfully launched with positive user feedback, achieving smooth checkout flows and increased customer engagement.",
    technologies: ["React", "Next.js", "Stripe", "Tailwind CSS"],
    testimonial_quote: "The platform perfectly captures our brand essence while providing our customers with an exceptional shopping experience.",
    testimonial_author: "Razan Fashion Team",
    testimonial_role: "Client",
    featured: true,
    published: true,
  },
  {
    slug: "yaseer-foundation",
    title: "Yaseer Foundation",
    category_slug: "web-design",
    short_description: "Islamic educational charity website with donation management, program showcases, and community engagement features.",
    client: "Yaseer Foundation",
    year: "2024",
    services: ["WordPress Development", "Donation Management", "Content Management", "Responsive Design"],
    cover_image_url: "/yaseer-foundation-home.jpg",
    images: ["/yaseer-foundation-home.jpg", "/yaseer-foundation-programs.jpg", "/yaseer-foundation-donate.jpg"],
    external_link: "https://yaseer-foundation.org",
    challenge: "Develop a comprehensive charity website that effectively communicates the foundation's mission, showcases educational programs, and provides a secure donation system.",
    solution: "Created a WordPress-based website with custom donation management, program showcases, and engaging content sections.",
    process: [
      "Planning - Defined site structure and donation workflows",
      "Design - Developed brand-aligned visual design",
      "Development - Built custom WordPress theme with donation features",
      "Content - Organized programs and impact stories",
      "Optimization - Enhanced performance and SEO",
    ],
    results: "Launched a professional charity website that effectively engages donors and showcases educational programs.",
    technologies: ["WordPress", "PHP", "MySQL", "CSS"],
    featured: false,
    published: true,
  },
  {
    slug: "alawnu-foundation",
    title: "Alawnu Foundation",
    category_slug: "web-design",
    short_description: "Humanitarian organization website with donation management, campaign showcases, and community outreach programs.",
    client: "Alawnu Foundation",
    year: "2024",
    services: ["Vue.js Development", "Campaign Management", "Donation System", "UI/UX Design"],
    cover_image_url: "/alawnu-foundation-home.jpg",
    images: ["/alawnu-foundation-home.jpg", "/alawnu-foundation-campaigns.jpg", "/alawnu-foundation-impact.jpg"],
    external_link: "https://alawnu.org",
    challenge: "Build a dynamic humanitarian organization website that showcases ongoing campaigns, manages donations effectively, and engages the community.",
    solution: "Developed a Vue.js-powered website with interactive campaign displays, secure donation processing, and compelling storytelling.",
    process: [
      "Research - Analyzed humanitarian sector best practices",
      "Architecture - Designed scalable Vue.js application structure",
      "Development - Built interactive components and donation flows",
      "Integration - Connected payment and campaign management systems",
      "Launch - Deployed with monitoring and analytics",
    ],
    results: "Created an engaging platform that effectively communicates the foundation's humanitarian mission.",
    technologies: ["Vue.js", "Nuxt.js", "Node.js", "Tailwind CSS"],
    featured: false,
    published: true,
  },
  {
    slug: "yaseer-institute",
    title: "Yaseer Institute",
    category_slug: "web-design",
    short_description: "Islamic educational platform offering structured learning programs for young Muslims with course management and progress tracking.",
    client: "Yaseer Institute",
    year: "2024",
    services: ["WordPress Development", "LMS Integration", "Course Management", "Student Portal"],
    cover_image_url: "/yaseer-institute-home.jpg",
    images: ["/yaseer-institute-home.jpg", "/yaseer-institute-courses.jpg", "/yaseer-institute-dashboard.jpg"],
    external_link: "https://yaseer-institute.org",
    challenge: "Create an educational platform that provides structured Islamic learning programs for young Muslims with effective course management.",
    solution: "Built a WordPress-based learning management system with course organization, progress tracking, and an intuitive student portal.",
    process: [
      "Requirements - Gathered educational program needs",
      "Design - Created student-friendly interface designs",
      "Development - Implemented LMS features and course structure",
      "Testing - Validated learning workflows with students",
      "Deployment - Launched with instructor training",
    ],
    results: "Successfully launched an educational platform that provides structured learning experiences.",
    technologies: ["WordPress", "LearnDash", "PHP", "JavaScript"],
    featured: false,
    published: true,
  },
  {
    slug: "triplexon",
    title: "Triplexon",
    category_slug: "web-design",
    short_description: "Industrial services platform providing expert consultation and immediate access to specialized help for oil, gas, and industrial sectors.",
    client: "Triplexon",
    year: "2024",
    services: ["WordPress Development", "Service Portal", "Consultation Booking", "Industry Solutions"],
    cover_image_url: "/triplexon-home.jpg",
    images: ["/triplexon-home.jpg", "/triplexon-services.jpg", "/triplexon-consultation.jpg"],
    external_link: "https://triplexon.com",
    challenge: "Develop a professional industrial services platform that connects clients with expert consultation.",
    solution: "Created a WordPress-based platform with service showcases, consultation booking, and industry-specific solutions.",
    process: [
      "Discovery - Researched industrial sector requirements",
      "Strategy - Defined service offerings and user journeys",
      "Design - Developed professional, industry-appropriate design",
      "Development - Built service portal and booking system",
      "Launch - Deployed with client onboarding support",
    ],
    results: "Launched a professional platform that effectively showcases industrial expertise.",
    technologies: ["WordPress", "PHP", "MySQL", "CSS"],
    featured: false,
    published: true,
  },
  {
    slug: "alf-foundation",
    title: "Alf Foundation",
    category_slug: "web-design",
    short_description: "Al-Farouk Humanitarian Foundation website with donation management, volunteer coordination, and impact tracking.",
    client: "Al-Farouk Humanitarian Foundation",
    year: "2024",
    services: ["WordPress Development", "Donation Platform", "Volunteer Management", "Impact Reporting"],
    cover_image_url: "/alf-foundation-home.jpg",
    images: ["/alf-foundation-home.jpg", "/alf-foundation-programs.jpg", "/alf-foundation-volunteer.jpg"],
    external_link: "https://alf-foundation.org",
    challenge: "Build a comprehensive humanitarian foundation website that manages donations, coordinates volunteers, and tracks impact.",
    solution: "Developed a WordPress-based platform with integrated donation management, volunteer coordination tools, and impact reporting.",
    process: [
      "Planning - Mapped donation and volunteer workflows",
      "Design - Created compassionate, mission-driven design",
      "Development - Built donation and volunteer management features",
      "Content - Organized programs and impact stories",
      "Launch - Deployed with training for foundation staff",
    ],
    results: "Created a comprehensive platform that effectively manages humanitarian operations.",
    technologies: ["WordPress", "PHP", "MySQL", "JavaScript"],
    featured: false,
    published: true,
  },
]

async function seedProjects() {
  console.log('Starting project seeding...')

  // First, fetch all categories to get their IDs
  const { data: categories, error: catError } = await supabase
    .from('categories')
    .select('id, slug')

  if (catError) {
    console.error('Error fetching categories:', catError)
    return
  }

  // Create category slug to ID mapping
  categoryMap = categories.reduce((acc, cat) => {
    acc[cat.slug] = cat.id
    return acc
  }, {} as Record<string, string>)

  console.log('Category mapping:', categoryMap)

  let insertedCount = 0
  let errorCount = 0

  for (const project of projects) {
    const categoryId = categoryMap[project.category_slug]
    
    if (!categoryId) {
      console.error(`Category not found for slug: ${project.category_slug}`)
      errorCount++
      continue
    }

    // Insert project
    const { data: insertedProject, error: projectError } = await supabase
      .from('projects')
      .upsert({
        slug: project.slug,
        title: project.title,
        short_description: project.short_description,
        full_description: project.challenge,
        cover_image_url: project.cover_image_url,
        category_id: categoryId,
        technologies: project.technologies || [],
        services: project.services || [],
        client: project.client,
        year: project.year,
        external_link: project.external_link,
        pdf_url: project.pdf_url,
        challenge: project.challenge,
        solution: project.solution,
        process: project.process || [],
        results: project.results,
        testimonial_quote: project.testimonial_quote,
        testimonial_author: project.testimonial_author,
        testimonial_role: project.testimonial_role,
        featured: project.featured || false,
        published: project.published || true,
        display_order: insertedCount,
      }, { onConflict: 'slug' })
      .select()
      .single()

    if (projectError) {
      console.error(`Error inserting project ${project.slug}:`, projectError)
      errorCount++
      continue
    }

    // Insert project images
    if (project.images && project.images.length > 0 && insertedProject) {
      const imageRecords = project.images.map((url, index) => ({
        project_id: insertedProject.id,
        image_url: url,
        alt_text: `${project.title} - Image ${index + 1}`,
        display_order: index,
      }))

      const { error: imagesError } = await supabase
        .from('project_images')
        .upsert(imageRecords, { onConflict: 'id' })

      if (imagesError) {
        console.error(`Error inserting images for ${project.slug}:`, imagesError)
      }
    }

    insertedCount++
    console.log(`Inserted: ${project.title}`)
  }

  console.log(`\nSeeding complete!`)
  console.log(`Successfully inserted: ${insertedCount} projects`)
  console.log(`Errors: ${errorCount}`)
}

seedProjects()
